baseURL: "https://yudiwiratama.github.io"
title: mynotes
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-182251419-3

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Yudi Putra Wiratamaa
    description: "My Journey Of Learning"
    keywords: [Blog, Portfolio, PaperMod]
    author: Yudi Putra Wiratama
    # author: ["Me", "You"] # multiple authors
    # images: [""]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        # icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: no # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "My Learning Journal"
        Content: Keep The Faith

    socialIcons:
        - name: email
          url: "mailto:yudiwiratama50@gmail.com"
        - name: linkedin
          url: "https://www.linkedin.com/in/yudi-wiratama"
        - name: instagram
          url: "https://instagram.com/@yudiputrawiratama"
        - name: telegram
          url: "https://t.me/Yudiputrawiratama"
        - name: twitter
          url: "https://twitter.com/-"
        - name: github
          url: "https://github.com/yudiwiratama"

    analytics:
        google:
            SiteVerificationTag: "7xkl7tm1-iJxieMKGetoXQpqJffAVKatOFgXg7ddX_Y"
        #bing:
        #    SiteVerificationTag: "XYZabc"
        #yandex:
        #    SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/yudiwiratama/yudiwiratama.github.io/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 10
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary